const forecast = {
  "@context": [
      "https://geojson.org/geojson-ld/geojson-context.jsonld",
      {
          "@version": "1.1",
          "wx": "https://api.weather.gov/ontology#",
          "geo": "http://www.opengis.net/ont/geosparql#",
          "unit": "http://codes.wmo.int/common/unit/",
          "@vocab": "https://api.weather.gov/ontology#"
      }
  ],
  "type": "Feature",
  "geometry": {
      "type": "Polygon",
      "coordinates": [
          [
              [
                  -78.796786400000002,
                  35.8429188
              ],
              [
                  -78.800083000000001,
                  35.820660500000002
              ],
              [
                  -78.772625500000004,
                  35.817985100000001
              ],
              [
                  -78.769323499999999,
                  35.840243000000001
              ],
              [
                  -78.796786400000002,
                  35.8429188
              ]
          ]
      ]
  },
  "properties": {
      "updated": "2021-12-17T12:11:10+00:00",
      "units": "us",
      "forecastGenerator": "HourlyForecastGenerator",
      "generatedAt": "2021-12-17T18:28:57+00:00",
      "updateTime": "2021-12-17T12:11:10+00:00",
      "validTimes": "2021-12-17T06:00:00+00:00/P7DT7H",
      "elevation": {
          "unitCode": "wmoUnit:m",
          "value": 92.049599999999998
      },
      "periods": [
          {
              "number": 1,
              "name": "",
              "startTime": "2021-12-17T13:00:00-05:00",
              "endTime": "2021-12-17T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 67,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 2,
              "name": "",
              "startTime": "2021-12-17T14:00:00-05:00",
              "endTime": "2021-12-17T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 68,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 3,
              "name": "",
              "startTime": "2021-12-17T15:00:00-05:00",
              "endTime": "2021-12-17T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 69,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 4,
              "name": "",
              "startTime": "2021-12-17T16:00:00-05:00",
              "endTime": "2021-12-17T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 69,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 5,
              "name": "",
              "startTime": "2021-12-17T17:00:00-05:00",
              "endTime": "2021-12-17T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 66,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 6,
              "name": "",
              "startTime": "2021-12-17T18:00:00-05:00",
              "endTime": "2021-12-17T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 63,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 7,
              "name": "",
              "startTime": "2021-12-17T19:00:00-05:00",
              "endTime": "2021-12-17T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 60,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 8,
              "name": "",
              "startTime": "2021-12-17T20:00:00-05:00",
              "endTime": "2021-12-17T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 60,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 9,
              "name": "",
              "startTime": "2021-12-17T21:00:00-05:00",
              "endTime": "2021-12-17T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 59,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 10,
              "name": "",
              "startTime": "2021-12-17T22:00:00-05:00",
              "endTime": "2021-12-17T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 59,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 11,
              "name": "",
              "startTime": "2021-12-17T23:00:00-05:00",
              "endTime": "2021-12-18T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "S",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 12,
              "name": "",
              "startTime": "2021-12-18T00:00:00-05:00",
              "endTime": "2021-12-18T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 13,
              "name": "",
              "startTime": "2021-12-18T01:00:00-05:00",
              "endTime": "2021-12-18T02:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/ovc?size=small",
              "shortForecast": "Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 14,
              "name": "",
              "startTime": "2021-12-18T02:00:00-05:00",
              "endTime": "2021-12-18T03:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/ovc?size=small",
              "shortForecast": "Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 15,
              "name": "",
              "startTime": "2021-12-18T03:00:00-05:00",
              "endTime": "2021-12-18T04:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/ovc?size=small",
              "shortForecast": "Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 16,
              "name": "",
              "startTime": "2021-12-18T04:00:00-05:00",
              "endTime": "2021-12-18T05:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/ovc?size=small",
              "shortForecast": "Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 17,
              "name": "",
              "startTime": "2021-12-18T05:00:00-05:00",
              "endTime": "2021-12-18T06:00:00-05:00",
              "isDaytime": false,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
              "shortForecast": "Patchy Drizzle",
              "detailedForecast": ""
          },
          {
              "number": 18,
              "name": "",
              "startTime": "2021-12-18T06:00:00-05:00",
              "endTime": "2021-12-18T07:00:00-05:00",
              "isDaytime": true,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Patchy Drizzle",
              "detailedForecast": ""
          },
          {
              "number": 19,
              "name": "",
              "startTime": "2021-12-18T07:00:00-05:00",
              "endTime": "2021-12-18T08:00:00-05:00",
              "isDaytime": true,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Patchy Drizzle",
              "detailedForecast": ""
          },
          {
              "number": 20,
              "name": "",
              "startTime": "2021-12-18T08:00:00-05:00",
              "endTime": "2021-12-18T09:00:00-05:00",
              "isDaytime": true,
              "temperature": 59,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Patchy Drizzle",
              "detailedForecast": ""
          },
          {
              "number": 21,
              "name": "",
              "startTime": "2021-12-18T09:00:00-05:00",
              "endTime": "2021-12-18T10:00:00-05:00",
              "isDaytime": true,
              "temperature": 60,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Patchy Drizzle",
              "detailedForecast": ""
          },
          {
              "number": 22,
              "name": "",
              "startTime": "2021-12-18T10:00:00-05:00",
              "endTime": "2021-12-18T11:00:00-05:00",
              "isDaytime": true,
              "temperature": 62,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Slight Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 23,
              "name": "",
              "startTime": "2021-12-18T11:00:00-05:00",
              "endTime": "2021-12-18T12:00:00-05:00",
              "isDaytime": true,
              "temperature": 65,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 24,
              "name": "",
              "startTime": "2021-12-18T12:00:00-05:00",
              "endTime": "2021-12-18T13:00:00-05:00",
              "isDaytime": true,
              "temperature": 67,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 25,
              "name": "",
              "startTime": "2021-12-18T13:00:00-05:00",
              "endTime": "2021-12-18T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 68,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 26,
              "name": "",
              "startTime": "2021-12-18T14:00:00-05:00",
              "endTime": "2021-12-18T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 70,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 27,
              "name": "",
              "startTime": "2021-12-18T15:00:00-05:00",
              "endTime": "2021-12-18T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 72,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 28,
              "name": "",
              "startTime": "2021-12-18T16:00:00-05:00",
              "endTime": "2021-12-18T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 69,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 29,
              "name": "",
              "startTime": "2021-12-18T17:00:00-05:00",
              "endTime": "2021-12-18T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 67,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 30,
              "name": "",
              "startTime": "2021-12-18T18:00:00-05:00",
              "endTime": "2021-12-18T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 66,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 31,
              "name": "",
              "startTime": "2021-12-18T19:00:00-05:00",
              "endTime": "2021-12-18T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 65,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 32,
              "name": "",
              "startTime": "2021-12-18T20:00:00-05:00",
              "endTime": "2021-12-18T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 65,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 33,
              "name": "",
              "startTime": "2021-12-18T21:00:00-05:00",
              "endTime": "2021-12-18T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 64,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 34,
              "name": "",
              "startTime": "2021-12-18T22:00:00-05:00",
              "endTime": "2021-12-18T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 64,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 35,
              "name": "",
              "startTime": "2021-12-18T23:00:00-05:00",
              "endTime": "2021-12-19T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 64,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 36,
              "name": "",
              "startTime": "2021-12-19T00:00:00-05:00",
              "endTime": "2021-12-19T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 63,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 37,
              "name": "",
              "startTime": "2021-12-19T01:00:00-05:00",
              "endTime": "2021-12-19T02:00:00-05:00",
              "isDaytime": false,
              "temperature": 63,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 38,
              "name": "",
              "startTime": "2021-12-19T02:00:00-05:00",
              "endTime": "2021-12-19T03:00:00-05:00",
              "isDaytime": false,
              "temperature": 63,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 39,
              "name": "",
              "startTime": "2021-12-19T03:00:00-05:00",
              "endTime": "2021-12-19T04:00:00-05:00",
              "isDaytime": false,
              "temperature": 62,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 40,
              "name": "",
              "startTime": "2021-12-19T04:00:00-05:00",
              "endTime": "2021-12-19T05:00:00-05:00",
              "isDaytime": false,
              "temperature": 62,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 41,
              "name": "",
              "startTime": "2021-12-19T05:00:00-05:00",
              "endTime": "2021-12-19T06:00:00-05:00",
              "isDaytime": false,
              "temperature": 60,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 42,
              "name": "",
              "startTime": "2021-12-19T06:00:00-05:00",
              "endTime": "2021-12-19T07:00:00-05:00",
              "isDaytime": true,
              "temperature": 58,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 43,
              "name": "",
              "startTime": "2021-12-19T07:00:00-05:00",
              "endTime": "2021-12-19T08:00:00-05:00",
              "isDaytime": true,
              "temperature": 57,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 44,
              "name": "",
              "startTime": "2021-12-19T08:00:00-05:00",
              "endTime": "2021-12-19T09:00:00-05:00",
              "isDaytime": true,
              "temperature": 56,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 45,
              "name": "",
              "startTime": "2021-12-19T09:00:00-05:00",
              "endTime": "2021-12-19T10:00:00-05:00",
              "isDaytime": true,
              "temperature": 54,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "12 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 46,
              "name": "",
              "startTime": "2021-12-19T10:00:00-05:00",
              "endTime": "2021-12-19T11:00:00-05:00",
              "isDaytime": true,
              "temperature": 56,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "13 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 47,
              "name": "",
              "startTime": "2021-12-19T11:00:00-05:00",
              "endTime": "2021-12-19T12:00:00-05:00",
              "isDaytime": true,
              "temperature": 56,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "13 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 48,
              "name": "",
              "startTime": "2021-12-19T12:00:00-05:00",
              "endTime": "2021-12-19T13:00:00-05:00",
              "isDaytime": true,
              "temperature": 57,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "12 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Rain Showers Likely",
              "detailedForecast": ""
          },
          {
              "number": 49,
              "name": "",
              "startTime": "2021-12-19T13:00:00-05:00",
              "endTime": "2021-12-19T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 57,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "10 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Slight Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 50,
              "name": "",
              "startTime": "2021-12-19T14:00:00-05:00",
              "endTime": "2021-12-19T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 57,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Slight Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 51,
              "name": "",
              "startTime": "2021-12-19T15:00:00-05:00",
              "endTime": "2021-12-19T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 56,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "9 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
              "shortForecast": "Slight Chance Rain Showers",
              "detailedForecast": ""
          },
          {
              "number": 52,
              "name": "",
              "startTime": "2021-12-19T16:00:00-05:00",
              "endTime": "2021-12-19T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 55,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 53,
              "name": "",
              "startTime": "2021-12-19T17:00:00-05:00",
              "endTime": "2021-12-19T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 51,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 54,
              "name": "",
              "startTime": "2021-12-19T18:00:00-05:00",
              "endTime": "2021-12-19T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 47,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 55,
              "name": "",
              "startTime": "2021-12-19T19:00:00-05:00",
              "endTime": "2021-12-19T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 44,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 56,
              "name": "",
              "startTime": "2021-12-19T20:00:00-05:00",
              "endTime": "2021-12-19T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 42,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 57,
              "name": "",
              "startTime": "2021-12-19T21:00:00-05:00",
              "endTime": "2021-12-19T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 41,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 58,
              "name": "",
              "startTime": "2021-12-19T22:00:00-05:00",
              "endTime": "2021-12-19T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 59,
              "name": "",
              "startTime": "2021-12-19T23:00:00-05:00",
              "endTime": "2021-12-20T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 60,
              "name": "",
              "startTime": "2021-12-20T00:00:00-05:00",
              "endTime": "2021-12-20T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 37,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 61,
              "name": "",
              "startTime": "2021-12-20T01:00:00-05:00",
              "endTime": "2021-12-20T02:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 62,
              "name": "",
              "startTime": "2021-12-20T02:00:00-05:00",
              "endTime": "2021-12-20T03:00:00-05:00",
              "isDaytime": false,
              "temperature": 35,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 63,
              "name": "",
              "startTime": "2021-12-20T03:00:00-05:00",
              "endTime": "2021-12-20T04:00:00-05:00",
              "isDaytime": false,
              "temperature": 34,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 64,
              "name": "",
              "startTime": "2021-12-20T04:00:00-05:00",
              "endTime": "2021-12-20T05:00:00-05:00",
              "isDaytime": false,
              "temperature": 33,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 65,
              "name": "",
              "startTime": "2021-12-20T05:00:00-05:00",
              "endTime": "2021-12-20T06:00:00-05:00",
              "isDaytime": false,
              "temperature": 32,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 66,
              "name": "",
              "startTime": "2021-12-20T06:00:00-05:00",
              "endTime": "2021-12-20T07:00:00-05:00",
              "isDaytime": true,
              "temperature": 32,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 67,
              "name": "",
              "startTime": "2021-12-20T07:00:00-05:00",
              "endTime": "2021-12-20T08:00:00-05:00",
              "isDaytime": true,
              "temperature": 30,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 68,
              "name": "",
              "startTime": "2021-12-20T08:00:00-05:00",
              "endTime": "2021-12-20T09:00:00-05:00",
              "isDaytime": true,
              "temperature": 33,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 69,
              "name": "",
              "startTime": "2021-12-20T09:00:00-05:00",
              "endTime": "2021-12-20T10:00:00-05:00",
              "isDaytime": true,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 70,
              "name": "",
              "startTime": "2021-12-20T10:00:00-05:00",
              "endTime": "2021-12-20T11:00:00-05:00",
              "isDaytime": true,
              "temperature": 39,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 71,
              "name": "",
              "startTime": "2021-12-20T11:00:00-05:00",
              "endTime": "2021-12-20T12:00:00-05:00",
              "isDaytime": true,
              "temperature": 41,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 72,
              "name": "",
              "startTime": "2021-12-20T12:00:00-05:00",
              "endTime": "2021-12-20T13:00:00-05:00",
              "isDaytime": true,
              "temperature": 44,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 73,
              "name": "",
              "startTime": "2021-12-20T13:00:00-05:00",
              "endTime": "2021-12-20T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 46,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 74,
              "name": "",
              "startTime": "2021-12-20T14:00:00-05:00",
              "endTime": "2021-12-20T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 46,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 75,
              "name": "",
              "startTime": "2021-12-20T15:00:00-05:00",
              "endTime": "2021-12-20T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 47,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 76,
              "name": "",
              "startTime": "2021-12-20T16:00:00-05:00",
              "endTime": "2021-12-20T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 47,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 77,
              "name": "",
              "startTime": "2021-12-20T17:00:00-05:00",
              "endTime": "2021-12-20T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 44,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 78,
              "name": "",
              "startTime": "2021-12-20T18:00:00-05:00",
              "endTime": "2021-12-20T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 42,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 79,
              "name": "",
              "startTime": "2021-12-20T19:00:00-05:00",
              "endTime": "2021-12-20T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 39,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 80,
              "name": "",
              "startTime": "2021-12-20T20:00:00-05:00",
              "endTime": "2021-12-20T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "E",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 81,
              "name": "",
              "startTime": "2021-12-20T21:00:00-05:00",
              "endTime": "2021-12-20T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 82,
              "name": "",
              "startTime": "2021-12-20T22:00:00-05:00",
              "endTime": "2021-12-20T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 37,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 83,
              "name": "",
              "startTime": "2021-12-20T23:00:00-05:00",
              "endTime": "2021-12-21T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 37,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "NE",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 84,
              "name": "",
              "startTime": "2021-12-21T00:00:00-05:00",
              "endTime": "2021-12-21T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 85,
              "name": "",
              "startTime": "2021-12-21T01:00:00-05:00",
              "endTime": "2021-12-21T02:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 86,
              "name": "",
              "startTime": "2021-12-21T02:00:00-05:00",
              "endTime": "2021-12-21T03:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "1 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 87,
              "name": "",
              "startTime": "2021-12-21T03:00:00-05:00",
              "endTime": "2021-12-21T04:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 88,
              "name": "",
              "startTime": "2021-12-21T04:00:00-05:00",
              "endTime": "2021-12-21T05:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 89,
              "name": "",
              "startTime": "2021-12-21T05:00:00-05:00",
              "endTime": "2021-12-21T06:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 90,
              "name": "",
              "startTime": "2021-12-21T06:00:00-05:00",
              "endTime": "2021-12-21T07:00:00-05:00",
              "isDaytime": true,
              "temperature": 35,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 91,
              "name": "",
              "startTime": "2021-12-21T07:00:00-05:00",
              "endTime": "2021-12-21T08:00:00-05:00",
              "isDaytime": true,
              "temperature": 35,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 92,
              "name": "",
              "startTime": "2021-12-21T08:00:00-05:00",
              "endTime": "2021-12-21T09:00:00-05:00",
              "isDaytime": true,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 93,
              "name": "",
              "startTime": "2021-12-21T09:00:00-05:00",
              "endTime": "2021-12-21T10:00:00-05:00",
              "isDaytime": true,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 94,
              "name": "",
              "startTime": "2021-12-21T10:00:00-05:00",
              "endTime": "2021-12-21T11:00:00-05:00",
              "isDaytime": true,
              "temperature": 43,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 95,
              "name": "",
              "startTime": "2021-12-21T11:00:00-05:00",
              "endTime": "2021-12-21T12:00:00-05:00",
              "isDaytime": true,
              "temperature": 45,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 96,
              "name": "",
              "startTime": "2021-12-21T12:00:00-05:00",
              "endTime": "2021-12-21T13:00:00-05:00",
              "isDaytime": true,
              "temperature": 47,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 97,
              "name": "",
              "startTime": "2021-12-21T13:00:00-05:00",
              "endTime": "2021-12-21T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 49,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 98,
              "name": "",
              "startTime": "2021-12-21T14:00:00-05:00",
              "endTime": "2021-12-21T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 49,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 99,
              "name": "",
              "startTime": "2021-12-21T15:00:00-05:00",
              "endTime": "2021-12-21T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 50,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 100,
              "name": "",
              "startTime": "2021-12-21T16:00:00-05:00",
              "endTime": "2021-12-21T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 50,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 101,
              "name": "",
              "startTime": "2021-12-21T17:00:00-05:00",
              "endTime": "2021-12-21T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 48,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 102,
              "name": "",
              "startTime": "2021-12-21T18:00:00-05:00",
              "endTime": "2021-12-21T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 46,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
              "shortForecast": "Slight Chance Light Rain",
              "detailedForecast": ""
          },
          {
              "number": 103,
              "name": "",
              "startTime": "2021-12-21T19:00:00-05:00",
              "endTime": "2021-12-21T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 44,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 104,
              "name": "",
              "startTime": "2021-12-21T20:00:00-05:00",
              "endTime": "2021-12-21T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 43,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 105,
              "name": "",
              "startTime": "2021-12-21T21:00:00-05:00",
              "endTime": "2021-12-21T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 43,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 106,
              "name": "",
              "startTime": "2021-12-21T22:00:00-05:00",
              "endTime": "2021-12-21T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 42,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 107,
              "name": "",
              "startTime": "2021-12-21T23:00:00-05:00",
              "endTime": "2021-12-22T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 41,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 108,
              "name": "",
              "startTime": "2021-12-22T00:00:00-05:00",
              "endTime": "2021-12-22T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 109,
              "name": "",
              "startTime": "2021-12-22T01:00:00-05:00",
              "endTime": "2021-12-22T02:00:00-05:00",
              "isDaytime": false,
              "temperature": 39,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 110,
              "name": "",
              "startTime": "2021-12-22T02:00:00-05:00",
              "endTime": "2021-12-22T03:00:00-05:00",
              "isDaytime": false,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 111,
              "name": "",
              "startTime": "2021-12-22T03:00:00-05:00",
              "endTime": "2021-12-22T04:00:00-05:00",
              "isDaytime": false,
              "temperature": 37,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 112,
              "name": "",
              "startTime": "2021-12-22T04:00:00-05:00",
              "endTime": "2021-12-22T05:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 113,
              "name": "",
              "startTime": "2021-12-22T05:00:00-05:00",
              "endTime": "2021-12-22T06:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
              "shortForecast": "Mostly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 114,
              "name": "",
              "startTime": "2021-12-22T06:00:00-05:00",
              "endTime": "2021-12-22T07:00:00-05:00",
              "isDaytime": true,
              "temperature": 35,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 115,
              "name": "",
              "startTime": "2021-12-22T07:00:00-05:00",
              "endTime": "2021-12-22T08:00:00-05:00",
              "isDaytime": true,
              "temperature": 35,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 116,
              "name": "",
              "startTime": "2021-12-22T08:00:00-05:00",
              "endTime": "2021-12-22T09:00:00-05:00",
              "isDaytime": true,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 117,
              "name": "",
              "startTime": "2021-12-22T09:00:00-05:00",
              "endTime": "2021-12-22T10:00:00-05:00",
              "isDaytime": true,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
              "shortForecast": "Partly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 118,
              "name": "",
              "startTime": "2021-12-22T10:00:00-05:00",
              "endTime": "2021-12-22T11:00:00-05:00",
              "isDaytime": true,
              "temperature": 43,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 119,
              "name": "",
              "startTime": "2021-12-22T11:00:00-05:00",
              "endTime": "2021-12-22T12:00:00-05:00",
              "isDaytime": true,
              "temperature": 45,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "8 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 120,
              "name": "",
              "startTime": "2021-12-22T12:00:00-05:00",
              "endTime": "2021-12-22T13:00:00-05:00",
              "isDaytime": true,
              "temperature": 48,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 121,
              "name": "",
              "startTime": "2021-12-22T13:00:00-05:00",
              "endTime": "2021-12-22T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 50,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "7 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 122,
              "name": "",
              "startTime": "2021-12-22T14:00:00-05:00",
              "endTime": "2021-12-22T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 50,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 123,
              "name": "",
              "startTime": "2021-12-22T15:00:00-05:00",
              "endTime": "2021-12-22T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 50,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 124,
              "name": "",
              "startTime": "2021-12-22T16:00:00-05:00",
              "endTime": "2021-12-22T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 50,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 125,
              "name": "",
              "startTime": "2021-12-22T17:00:00-05:00",
              "endTime": "2021-12-22T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 47,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
              "shortForecast": "Mostly Sunny",
              "detailedForecast": ""
          },
          {
              "number": 126,
              "name": "",
              "startTime": "2021-12-22T18:00:00-05:00",
              "endTime": "2021-12-22T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 45,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 127,
              "name": "",
              "startTime": "2021-12-22T19:00:00-05:00",
              "endTime": "2021-12-22T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 42,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 128,
              "name": "",
              "startTime": "2021-12-22T20:00:00-05:00",
              "endTime": "2021-12-22T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 41,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 129,
              "name": "",
              "startTime": "2021-12-22T21:00:00-05:00",
              "endTime": "2021-12-22T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 130,
              "name": "",
              "startTime": "2021-12-22T22:00:00-05:00",
              "endTime": "2021-12-22T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 39,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 131,
              "name": "",
              "startTime": "2021-12-22T23:00:00-05:00",
              "endTime": "2021-12-23T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 132,
              "name": "",
              "startTime": "2021-12-23T00:00:00-05:00",
              "endTime": "2021-12-23T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 38,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 133,
              "name": "",
              "startTime": "2021-12-23T01:00:00-05:00",
              "endTime": "2021-12-23T02:00:00-05:00",
              "isDaytime": false,
              "temperature": 37,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 134,
              "name": "",
              "startTime": "2021-12-23T02:00:00-05:00",
              "endTime": "2021-12-23T03:00:00-05:00",
              "isDaytime": false,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 135,
              "name": "",
              "startTime": "2021-12-23T03:00:00-05:00",
              "endTime": "2021-12-23T04:00:00-05:00",
              "isDaytime": false,
              "temperature": 35,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 136,
              "name": "",
              "startTime": "2021-12-23T04:00:00-05:00",
              "endTime": "2021-12-23T05:00:00-05:00",
              "isDaytime": false,
              "temperature": 34,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 137,
              "name": "",
              "startTime": "2021-12-23T05:00:00-05:00",
              "endTime": "2021-12-23T06:00:00-05:00",
              "isDaytime": false,
              "temperature": 34,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 138,
              "name": "",
              "startTime": "2021-12-23T06:00:00-05:00",
              "endTime": "2021-12-23T07:00:00-05:00",
              "isDaytime": true,
              "temperature": 33,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 139,
              "name": "",
              "startTime": "2021-12-23T07:00:00-05:00",
              "endTime": "2021-12-23T08:00:00-05:00",
              "isDaytime": true,
              "temperature": 33,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 140,
              "name": "",
              "startTime": "2021-12-23T08:00:00-05:00",
              "endTime": "2021-12-23T09:00:00-05:00",
              "isDaytime": true,
              "temperature": 36,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "N",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 141,
              "name": "",
              "startTime": "2021-12-23T09:00:00-05:00",
              "endTime": "2021-12-23T10:00:00-05:00",
              "isDaytime": true,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 142,
              "name": "",
              "startTime": "2021-12-23T10:00:00-05:00",
              "endTime": "2021-12-23T11:00:00-05:00",
              "isDaytime": true,
              "temperature": 43,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 143,
              "name": "",
              "startTime": "2021-12-23T11:00:00-05:00",
              "endTime": "2021-12-23T12:00:00-05:00",
              "isDaytime": true,
              "temperature": 46,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 144,
              "name": "",
              "startTime": "2021-12-23T12:00:00-05:00",
              "endTime": "2021-12-23T13:00:00-05:00",
              "isDaytime": true,
              "temperature": 48,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "NW",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 145,
              "name": "",
              "startTime": "2021-12-23T13:00:00-05:00",
              "endTime": "2021-12-23T14:00:00-05:00",
              "isDaytime": true,
              "temperature": 51,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 146,
              "name": "",
              "startTime": "2021-12-23T14:00:00-05:00",
              "endTime": "2021-12-23T15:00:00-05:00",
              "isDaytime": true,
              "temperature": 51,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "6 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 147,
              "name": "",
              "startTime": "2021-12-23T15:00:00-05:00",
              "endTime": "2021-12-23T16:00:00-05:00",
              "isDaytime": true,
              "temperature": 51,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 148,
              "name": "",
              "startTime": "2021-12-23T16:00:00-05:00",
              "endTime": "2021-12-23T17:00:00-05:00",
              "isDaytime": true,
              "temperature": 51,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 149,
              "name": "",
              "startTime": "2021-12-23T17:00:00-05:00",
              "endTime": "2021-12-23T18:00:00-05:00",
              "isDaytime": true,
              "temperature": 48,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "5 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/day/few?size=small",
              "shortForecast": "Sunny",
              "detailedForecast": ""
          },
          {
              "number": 150,
              "name": "",
              "startTime": "2021-12-23T18:00:00-05:00",
              "endTime": "2021-12-23T19:00:00-05:00",
              "isDaytime": false,
              "temperature": 45,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/few?size=small",
              "shortForecast": "Mostly Clear",
              "detailedForecast": ""
          },
          {
              "number": 151,
              "name": "",
              "startTime": "2021-12-23T19:00:00-05:00",
              "endTime": "2021-12-23T20:00:00-05:00",
              "isDaytime": false,
              "temperature": 42,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "SW",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 152,
              "name": "",
              "startTime": "2021-12-23T20:00:00-05:00",
              "endTime": "2021-12-23T21:00:00-05:00",
              "isDaytime": false,
              "temperature": 41,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 153,
              "name": "",
              "startTime": "2021-12-23T21:00:00-05:00",
              "endTime": "2021-12-23T22:00:00-05:00",
              "isDaytime": false,
              "temperature": 41,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 154,
              "name": "",
              "startTime": "2021-12-23T22:00:00-05:00",
              "endTime": "2021-12-23T23:00:00-05:00",
              "isDaytime": false,
              "temperature": 40,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 155,
              "name": "",
              "startTime": "2021-12-23T23:00:00-05:00",
              "endTime": "2021-12-24T00:00:00-05:00",
              "isDaytime": false,
              "temperature": 39,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "2 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          },
          {
              "number": 156,
              "name": "",
              "startTime": "2021-12-24T00:00:00-05:00",
              "endTime": "2021-12-24T01:00:00-05:00",
              "isDaytime": false,
              "temperature": 39,
              "temperatureUnit": "F",
              "temperatureTrend": null,
              "windSpeed": "3 mph",
              "windDirection": "W",
              "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
              "shortForecast": "Partly Cloudy",
              "detailedForecast": ""
          }
      ]
  }
}

// takes in an hourly api call and a date obj formatted in YYYY-MM-DD and returns a list of hourly weather objects
const hourlyDeconstructor = (forecast, dateObj) => {
  const hourlyForecastObj = forecast.properties.periods
  // get the date from the dateObj
  const date = dateObj.split('-')[2]
  const hourArr = hourlyForecastObj.map( (hour) => {
    // generate a new date time for each hour to compare against the hour
    const hourDateObj = new Date(hour.startTime)
    if (hourDateObj.getDate() == date) {
      return obj = {
        startHour : hour.startTime,
        windSpeed : hour.windSpeed,
        windDirection : hour.windDirection,
        temperature : hour.temperature
      }
    } 
  })
  // filters all that are null or undefined
  const filteredHourArr = hourArr.filter((obj) => {
    return obj
  } )
  console.log(filteredHourArr)
  return filteredHourArr
}

const helperFunctions = {
  hourlyDeconstructor
}

export default helperFunctions 

