# Generated by Django 3.2.9 on 2021-12-15 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=5)),
                ('latitude', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=255)),
                ('trip_date', models.DateField()),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core_app.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunrise', models.CharField(max_length=100)),
                ('sunset', models.CharField(max_length=100)),
                ('maxwind', models.CharField(max_length=10)),
                ('minwind', models.CharField(max_length=10)),
                ('avgtemp', models.CharField(max_length=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='core_app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to='core_app.profile')),
            ],
        ),
    ]
