# Generated by Django 3.2.9 on 2021-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='max_wind',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='min_wind',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
